server:
  mode: "local"
  listen_address: "0.0.0.0:30343"
#  listen_address_tls: "0.0.0.0:30344"
#  tls_cert_file: "server.crt" # Required if listen_address_tls is set
#  tls_key_file: "server.key"  # Required if listen_address_tls is set
  idle_timeout: 30m
  server_operational_log_level: "debug"

# Settings for when server.mode is "local"
local_storage:
  log_directory: "/tmp/gosudo-io"

relay:
  upstream_host: "127.0.0.1:30344"
  use_tls: false
  connect_timeout: 15s
  relay_cache_directory: "/tmp/sudosrv-cache"
  reconnect_attempts: -1
