#!/usr/bin/env python3
"""Render docs/logsrvd-reference/CONFORMANCE.md from conformance-data.json.

Run from anywhere:  python3 docs/logsrvd-reference/generate-conformance.py

The verdict data lives in conformance-data.json, CHECKED IN next to this script.
It used to be read out of a session scratchpad, which meant the matrix could not
be regenerated once that session expired -- and it did expire, taking the full
text of 185 notes with it (they survive only as the clipped forms the previous
render had already written into the table). Do not move the data back out of the
repository.

To re-grade a requirement: edit its entry in conformance-data.json and re-run
this. Never hand-edit CONFORMANCE.md; it is overwritten wholesale.
"""
import collections
import json
import os
import re
import sys

DOCS = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(DOCS, "conformance-data.json")

SUBSYS = [
    ("ARCH",  "01-architecture.md",     "Daemon Architecture & Connection Lifecycle"),
    ("PROTO", "02-protocol.md",         "Wire Protocol & Message State Machine"),
    ("CONF",  "03-configuration.md",    "Configuration Surface & Defaults"),
    ("IOLOG", "04-local-storage.md",    "Local I/O Log Storage Format"),
    ("RELAY", "05-relay.md",            "Relay Mode & Store-and-Forward"),
    ("TLS",   "06-tls-and-security.md", "TLS, Authentication & Security Posture"),
    ("PROD",  "07-producer.md",         "Producer-Side Recording & Timing"),
]
STATUSES = ["MATCH", "INTENTIONAL", "PARTIAL", "DIVERGENT", "ABSENT", "NA"]
SEVERITIES = ["breaking", "high", "medium", "low", "informational"]
SEVRANK = {s: i for i, s in enumerate(SEVERITIES)} | {"none": 5}

REFERENCE_SHA = "36f7128256a93571ec378daa5c209d6883036d31"
REFERENCE_VERSION = "sudo 1.9.18"
REFERENCE_DATE = "2026-07-19"


def titles():
    """Pull the human title of each requirement out of its reference document."""
    out = {}
    for _, doc, _ in SUBSYS:
        p = os.path.join(DOCS, doc)
        if not os.path.exists(p):
            continue
        with open(p) as f:
            for m in re.finditer(r"^### ([A-Z]+-\d{3}) — (.+?)\s*$", f.read(), re.M):
                out[m.group(1)] = m.group(2).strip()
    return out


def esc(s):
    return (s or "").replace("|", "\\|").replace("\n", " ").strip()


def clip(s, n):
    s = esc(s)
    if len(s) <= n:
        return s
    # Values reconstructed from an earlier render are already clipped and can sit
    # a character or two over the limit. Re-clipping those ate one more character
    # on every regeneration, so a field that had been truncated once shrank a
    # little further each time the matrix was rebuilt. Anything already ending in
    # the ellipsis has had its turn.
    if s.endswith("…"):
        return s
    return s[: n - 1].rstrip() + "…"


def main():
    with open(DATA) as f:
        verdicts = json.load(f)["verdicts"]
    if not verdicts:
        sys.exit(f"no verdicts in {DATA}")
    T = titles()

    rows = []
    for v in verdicts:
        vid = v["id"]
        status = v["status"]
        sev = v.get("severity", "none")
        if status in ("MATCH", "NA"):
            sev = "none"
        rows.append({
            "id": vid,
            "prefix": vid.split("-")[0],
            "num": int(vid.split("-")[1]),
            "title": T.get(vid, ""),
            "status": status,
            "sev": sev,
            "go": v.get("go_source", "-"),
            "note": v.get("notes", ""),
        })
    rows.sort(key=lambda r: (r["prefix"], r["num"]))

    L = []
    A = L.append
    A("<!-- GENERATED by generate-conformance.py from conformance-data.json. Do not edit. -->")
    A("# Conformance Matrix — `sudosrv` vs. C `sudo_logsrvd`")
    A("")
    A(f"> **Reference:** {REFERENCE_VERSION} — `{REFERENCE_SHA}` ({REFERENCE_DATE})  ")
    A("> **Method:** every numbered requirement in [`01`](01-architecture.md)–[`07`](07-producer.md) "
      "was checked against the Go source, then every non-`MATCH` verdict was independently "
      "challenged by a second pass instructed to refute it. Verdict vocabulary is defined in "
      "[README.md](README.md#verdict-vocabulary).")
    A("")

    # ---- summary by subsystem -------------------------------------------------
    A("## Summary")
    A("")
    A("| Subsystem | Reqs | " + " | ".join(STATUSES) + " |")
    A("|---|--:|" + "--:|" * len(STATUSES))
    for pfx, doc, title in SUBSYS:
        sub = [r for r in rows if r["prefix"] == pfx]
        if not sub:
            continue
        c = collections.Counter(r["status"] for r in sub)
        A(f"| [{title}]({doc}) | {len(sub)} | " + " | ".join(str(c.get(s, 0)) for s in STATUSES) + " |")
    tot = collections.Counter(r["status"] for r in rows)
    A(f"| **Total** | **{len(rows)}** | " + " | ".join(f"**{tot.get(s,0)}**" for s in STATUSES) + " |")
    A("")

    sev = collections.Counter(r["sev"] for r in rows if r["status"] not in ("MATCH", "NA"))
    A("Severity of the " + str(sum(sev.values())) + " requirements that are not `MATCH`/`NA`:")
    A("")
    A("| " + " | ".join(SEVERITIES) + " |")
    A("|--:|--:|--:|--:|--:|")
    A("| " + " | ".join(str(sev.get(k, 0)) for k in SEVERITIES) + " |")
    A("")

    # ---- priority findings ----------------------------------------------------
    top = sorted([r for r in rows if r["sev"] in ("breaking", "high", "medium")],
                 key=lambda r: (SEVRANK[r["sev"]], r["prefix"], r["num"]))
    A("## Priority findings")
    A("")
    if not top:
        A("Nothing is graded `breaking`, `high` or `medium`. Every requirement that named a "
          "defect has been closed; what remains is graded `low` or `informational`, and is "
          "dominated by `INTENTIONAL` rows — deliberate divergences whose reasons are recorded "
          "in the code they describe.")
    else:
        A(f"{len(top)} requirements are graded `medium` or worse. These are the divergences "
          "worth acting on first.")
        A("")
        for r in top:
            doc = dict((p, d) for p, d, _ in SUBSYS)[r["prefix"]]
            A(f"### `{r['id']}` — {r['title']}")
            A("")
            A(f"**{r['status']}** · severity **{r['sev']}** · spec: "
              f"[{r['id']}]({doc}) · Go: `{r['go']}`")
            A("")
            A(f"{esc(r['note'])}")
            A("")
    A("")

    # ---- full matrix ----------------------------------------------------------
    A("## Full matrix")
    A("")
    A("`MATCH` rows are listed for completeness — they are the evidence that the requirement "
      "was actually checked, not skipped.")
    A("")
    for pfx, doc, title in SUBSYS:
        sub = [r for r in rows if r["prefix"] == pfx]
        if not sub:
            continue
        A(f"### {title}")
        A("")
        A(f"Spec: [`{doc}`]({doc})")
        A("")
        A("| ID | Requirement | Verdict | Sev | Go source | Consequence |")
        A("|---|---|---|---|---|---|")
        for r in sub:
            note = "—" if r["status"] == "MATCH" else clip(r["note"], 190)
            go = f"`{clip(r['go'], 60)}`" if r["go"] and r["go"] != "-" else "—"
            A(f"| `{r['id']}` | {clip(r['title'], 60)} | {r['status']} | {r['sev']} | {go} | {note} |")
        A("")

    out = os.path.join(DOCS, "CONFORMANCE.md")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {out}  ({len(L)} lines, {len(rows)} requirements)")
    print("status:", dict(tot))
    print("severity(non-match):", dict(sev))
    print("priority findings:", len(top))
    for r in top:
        print(f"   {r['id']:11s} {r['status']:11s} {r['sev']:8s} {r['title'][:60]}")


if __name__ == "__main__":
    main()
